import type { NextPage } from 'next';
import Head from 'next/head';

import HomeFeature from '../components/HomeFeature/HomeFeature';
import HomeNewReleaseMovies from '../components/HomeNewReleaseMovies/HomeNewReleaseMovies';
import HomeTopRateMovies from '../components/HomeTopRateMovie/HomeTopRateMovies';
import HomeTopTvShows from '../components/HomeTopTvShow/HomeTopTvShows';
import HomeTvShows from '../components/HomeTvShows/HomeTvShows';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Movie App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <HomeFeature />
                <div className={styles.wrapper}>
                    <div className={styles.inner}>
                        <HomeNewReleaseMovies />
                        <HomeTvShows />
                        <HomeTopRateMovies />
                        <HomeTopTvShows />
                    </div>
                </div>
            </div>
        </>
    );
};

export default Home;
